# This tells poetry to build the fortranformat virtual environment 
# in a .venv folder inside the fortranformat repository. This makes
# it easier to clean up afterwards (just delete the folder)
# and to find the virtual environment to use with the Jupyter
# notebooks.
[virtualenvs]
create = true
in-project = true