[tool.poetry]
name = "fortranformat"
version = "2.0.0"
description = "Mimics Fortran textual IO in Python."
authors = ["Brendan Arnold <brendanarnold@gmail.com>"]
repository = "https://github.com/brendanarnold/py-fortranformat"
keywords=['fortran', 'io', 'interface', 'format']
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Fortran',
    'Programming Language :: Python :: 3',
    'Topic :: Text Processing :: General',
    'Topic :: Software Development :: Interpreters',
    'Topic :: Scientific/Engineering',
]
packages = [
    { include = "fortranformat" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
twine = "^5.1.1"

[tool.pytest.ini_options]
testpaths = [
  "tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
